### ISSUE TITLE
IPFS checker external adapter

### ISSUE THREAD

**Issue by PatrickAlphaC** [iroiro/iroiro#50]
Awesome project here! I wanted to invite your team to host your IPFS external adapter on [market.link](https://market.link/search/adapters). 

It's a great way to show off your stuff some more, and help other engineers as well through your expertise!

**Comment by wild-mouse** [comment]
Hi @PatrickAlphaC , thanks for submitting a new issue for our repo!
But what should we do for this? This should be done with generarize our external adapter for everyone? And deploy a chainlink node to accept request?

**Comment by PatrickAlphaC** [comment]
https://docs.linkpool.io/docs/market_adapter_listing

Yep! This would be a way for anyone to deploy their own external adapter that you built!
